DROP TABLE IF EXISTS field;
CREATE TABLE field (field_id uuid PRIMARY KEY  DEFAULT gen_random_uuid(), form_id VARCHAR(255), field_details text, field_type_id VARCHAR(255),is_required bool,created_at bigint,updated_at bigint);
DROP TABLE IF EXISTS field_options;
CREATE TABLE field_options (option_id uuid PRIMARY KEY DEFAULT gen_random_uuid() , field_id VARCHAR(255), option_text text, option_value text,created_at bigint,updated_at bigint);
DROP TABLE IF EXISTS field_response;
CREATE TABLE field_response (field_response_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), response_id VARCHAR(255), field_id VARCHAR(255),is_selected bool, response_value text, field_option_id VARCHAR(255),created_at bigint,updated_at bigint);
DROP TABLE IF EXISTS field_type;
CREATE TABLE field_type (field_type_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), field_type VARCHAR(255), created_by VARCHAR(255),created_at bigint,updated_at bigint);
DROP TABLE IF EXISTS form;
CREATE TABLE form (form_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id VARCHAR(255), workspace_id VARCHAR(255), title text, is_favourites bool, description text, state VARCHAR(255),is_published bool,is_public bool,created_at bigint,updated_at bigint);
DROP TABLE IF EXISTS form_settings;
CREATE TABLE form_settings (setting_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), form_id VARCHAR(255),  allow_public bool, shuffle_questions bool, expiry_time bigint, allow_multiple_response bool, activation_start_time bigint, max_response_threshold bigint,thank_you_message text, created_at bigint,updated_at bigint);
DROP TABLE IF EXISTS response;
CREATE TABLE response (response_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),  user_id VARCHAR(255),form_id VARCHAR(255),submitted_at bigint,submission_status  VARCHAR(255),updated_at bigint);
DROP TABLE IF EXISTS form_style;
CREATE TABLE form_style (style_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), font VARCHAR(255), button_style VARCHAR(255), theme VARCHAR(255), form_id VARCHAR(255), background_color  VARCHAR(255), primary_color  VARCHAR(255),created_at bigint,updated_at bigint);
DROP TABLE IF EXISTS workspace;
CREATE TABLE workspace (workspace_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id VARCHAR(255), title  VARCHAR(255),description  VARCHAR(255),access  VARCHAR(255), form_ids text[], created_at bigint,updated_at bigint);
DROP TABLE IF EXISTS data_types;
CREATE TABLE data_types (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255), tenant_id VARCHAR(255),  description  VARCHAR(255),is_premium bool,is_active bool, created_by VARCHAR(255), groups TEXT[], rank bigint, min_length bigint, max_limit bigint,created_at bigint,updated_at bigint);
DROP TABLE IF EXISTS settings_meta_info;
CREATE TABLE settings_meta_info (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255), tenant_id VARCHAR(255), map_name  VARCHAR(255),  created_by VARCHAR(255), data_type  VARCHAR(255), is_premium bool,is_active bool,  created_at bigint,updated_at bigint);